server:
  port: 8181

spring:
  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      database: roadrating
      port: 27017
      host: localhost

#  jpa:
#    hibernate:
#      ddl-auto: create





