server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roadrating
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      database: roadrating
      port: 27017
      host: localhost

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create





